name: superheroes
description: Search for superheroes
publish_to: 'none'
version: 1.1.3+13
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.2
  collection: ^1.16.0
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  http: ^0.13.5
  json_annotation: ^4.6.0
  provider: ^6.0.3
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.2.0
  carapacik_lints: ^1.2.2
  icons_launcher: ^2.0.5
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - google_fonts/

icons_launcher:
  image_path: assets/ic_logo_border.png
  platforms:
    android:
      enable: true
      adaptive_background_image: assets/ic_background.png
      adaptive_foreground_image: assets/ic_foreground.png
      adaptive_round_image: assets/ic_foreground.png
    ios:
      enable: true
      image_path: assets/ic_logo.png
    web:
      enable: true
      image_path: assets/ic_logo_transparent.png
      favicon_path: assets/ic_logo_transparent.png
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true
