name: superheroes
description: Search for superheroes on superheroapi.com
publish_to: 'none'
version: 1.0.6+7
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  collection: ^1.16.0
  flutter:
    sdk: flutter
  google_fonts: ^2.3.2
  http: ^0.13.4
  json_annotation: ^4.5.0
  provider: ^6.0.2
  rxdart: ^0.27.3
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.1.11
  carapacik_lints:
    git:
      url: https://github.com/Carapacik/carapacik_lints.git
  flutter_native_splash: ^2.2.0+1
  icons_launcher: ^1.1.8
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - google_fonts/

flutter_icons:
  image_path: 'assets/ic_logo.png'
  adaptive_icon_background: 'assets/ic_background.png'
  adaptive_icon_foreground: 'assets/ic_foreground.png'
  remove_alpha_ios: false
  remove_alpha_macos: false
  android: true
  ios: true
  linux: true
  macos: true
  web: true
  windows: true

flutter_native_splash:
  color: '#10141E'
  image: 'assets/images/ironman.png'
  android: true
  ios: true
  linux: true
  macos: true
  web: true
  windows: true
  fullscreen: true
