name: superheroes
description: "Search for superheroes"
publish_to: 'none'
version: 1.1.4+14
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  provider: ^6.1.2
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.10
  carapacik_lints: ^1.8.1
  #flutter_launcher_icons: ^0.13.1
  #flutter_native_splash: ^2.4.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - google_fonts/

flutter_launcher_icons:
  image_path: "assets/app/ic_logo_border.png"
  android: true
  adaptive_icon_background: "assets/app/ic_background.png"
  adaptive_icon_foreground: "assets/app/ic_foreground.png"
  min_sdk_android: 24
  ios: "assets/app/ic_logo.png"
  macos:
    generate: true
  windows:
    generate: true

flutter_native_splash:
  color: "#10141E"
  image: "assets/app/ic_foreground.png"
  android: true
  ios: true
  web: true
