name: superheroes
description: Api with dio
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  google_fonts: ^2.1.0
  http: ^0.13.3
  json_annotation: ^4.0.1
  provider: ^6.0.0
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.4
  lint: ^1.6.0
  network_image_mock: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/images/
    - assets/icons/
    - .env