name: superheroes
description: Work with https://superheroapi.com
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  google_fonts: ^2.1.0
  http: ^0.13.3
  json_annotation: ^4.1.0
  provider: ^6.0.0
  rxdart: ^0.27.2
  shared_preferences: ^2.0.7

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.10.0
  json_serializable: ^5.0.0
  lint: ^1.7.2
  mockito: ^5.0.15
  network_image_mock: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/images/
    - assets/icons/
    - .env