name: superheroes
description: Work with open api

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  google_fonts: ^2.1.0
  http: ^0.13.3
  json_annotation: ^4.1.0
  provider: ^6.0.0
  rxdart: ^0.27.2
  shared_preferences: ^2.0.7

dev_dependencies:
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.10.0
  json_serializable: ^5.0.1
  network_image_mock: ^2.0.1
  rename: ^1.3.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - google_fonts/
    - assets/images/
    - assets/icons/
    - .env