name: superheroes
description: Work with open api
publish_to: 'none'
version: 1.0.5+6

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  google_fonts: ^2.3.1
  http: ^0.13.4
  json_annotation: ^4.4.0
  provider: ^6.0.2
  rxdart: ^0.27.3
  shared_preferences: ^2.0.13

dev_dependencies:
  build_runner: ^2.1.7
  flutter_launcher_icons_maker: ^0.10.2
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.13.0
  json_serializable: ^6.1.4
  lint: ^1.8.2
  mockito: ^5.0.17
  network_image_mock: ^2.0.1

flutter_icons:
  android: true
  ios: true
  web: true
  windows: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - google_fonts/
    - .env