name: github pages

on:
  push:
    branches:
      - main

jobs:
  pages:
    name: "Deploy on Github Pages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Build
        run: flutter build web
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_dir: ./build/web
